package generation;

public enum OllirAssistantType {
    BIN_OP,
    UN_OP_NEW_OBJ,
    UN_OP_NEW_ARRAY,
    UN_OP_NEG,
    VALUE,
    FIELD,
    STATEMENT_ASSIGN,
    STATEMENT,
    METHODCALL,
    METHOD,
    METHOD_ARGS,
    INDEXING,
    RETURN,
    METHOD_BODY,
    METHOD_HEADER,
    METHOD_DECLARATION,
    VAR_DECLARATION,
    CLASS_DECLARATION,
    LENGTH,
    ARRAY,
    CLASSOBJ,
    ITERATION_STATEMENT,
    COMPOUND_STATEMENT,
    SELECTION_STATEMENT
}
